"""Test constants to avoid magic values in tests."""

# Test threshold values
BIS_THRESHOLD_WARN = 85
BIS_THRESHOLD_WARN_DEFAULT = 80
BIS_THRESHOLD_FAIL = 65
STATIC_CLONE_HAMMING = 8
DYNAMIC_COV_JACCARD = 0.9
MOCK_ASSERT_THRESHOLD = 10

# Test budget values
BUDGET_WARN = 20
BUDGET_ERROR = 5

# Test configuration values
SIMILARITY_THRESHOLD = 0.8
BIS_THRESHOLD = 90
BIS_THRESHOLD_90 = 90
MAX_WORKERS = 4
LSP_PORT = 8080

# Test assertion values
TEST_LINE_NUMBER = 42
TEST_COLUMN_NUMBER = 10
TEST_CONFIDENCE = 0.8
TEST_BIS_SCORE = 85.5
TEST_INDENT = 2

# Test count values
EXPECTED_ERROR_COUNT_2 = 2
EXPECTED_ERROR_COUNT_3 = 3
EXPECTED_SUGGESTION_COUNT_5 = 5

# Test custom values
CUSTOM_THRESHOLD = 42.0
CUSTOM_THRESHOLD_ALT = 99.0
CUSTOM_BUDGET_WARN = 15
