name: CI (nox)

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Nox
        uses: wntrblm/nox@2025.05.01
        with:
          python-versions: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Run nox sessions
        run: |
          nox --sessions "tests-${{ matrix.python-version }}"

      - name: Run quality gates
        if: ${{ matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest' }}
        run: |
          nox -s lint type_check complexity security pyproject

      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false  # Don't fail CI if Codecov fails
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
